### ISSUE TITLE
Hello World Recipes needed

### ISSUE THREAD

**Issue by vsoch** [buildtesters/tutorials#1]
I'm testing these "basic" tutorials and most of them are failing out of the box, or require more advanced HPC knowledge. We need a dummy set of "hello world" tests that will work out of the box. Since I'm learning how to write these, I'll give a shot at this.

**Comment by shahzebsiddiqui** [comment]
Yea there are three hello world source code in https://github.com/HPC-buildtest/tutorials/tree/master/compilers/src for C, C++, Fortran. If we decide to change the YAML schema then certainly this will affect the build. 

By the way there are some examples of test scripts example in *master* branch see https://buildtest.readthedocs.io/en/latest/build_subcommand/build.html 

Note some of the features like ``--dry`` and ``--verbose`` were removed to clean up code.

**Comment by vsoch** [comment]
Are you sure about dry? I saw it still in the code I was looking at. Should I remove this in a future PR?

**Comment by shahzebsiddiqui** [comment]
I see it is still available https://github.com/HPC-buildtest/buildtest-framework/blob/devel/buildtest/tools/menu.py#L141 I mistaken it with the verbose option that was removed.  https://github.com/HPC-buildtest/buildtest-framework/commit/ccc89c482887fb2762089bd85ade6be79d7c7c7a

The idea with ``--dry`` was to provide output of test script without generating the test content. This would be useful for debugging purposes, when writing a YAML file. I think it makes sense to keep this feature but will need to be worked on after we get the build working.

**Comment by vsoch** [comment]
I agree.

**Comment by shahzebsiddiqui** [comment]
Closing this issue we have a sample hello world test for C, C++ and Fortran at https://github.com/buildtesters/tutorials/blob/master/apps/serial/hello.yml
